services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=contable
  iva_api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_SOURCE=postgresql://root:123@postgres/contable?sslmode=disable
    expose:
      - "3000"
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
  nginx:
    build:
      context: ./nginx/
      dockerfile: dockerfile
    ports:
      - "80:8080"
    depends_on:
      - "iva_api"
